ucFirst
js-tasks-ru/jsbasic-20221215_black-s-w-a-n pull request #3
Opened 2022-12-21 13:40 UTC by DovgiyA

2022-12-21 13:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-21 13:49 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-21 14:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-21 14:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-12-21 15:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-21 15:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-21 15:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-12-22 03:57 UTC, koalex requested changes
Исправить 1-4

2022-12-22 03:57 UTC, koalex commented on 1-module/4-task/index.js
> +  if (str.includes('1XbeT') || str.includes('xxx')) {
Тут задачу нужно решить **без учёта регистра**, вы посмотрели в тесты) Надо исправить

2022-12-22 05:58 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-22 06:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-12-22 09:14 UTC, koalex approved these changes

2022-12-22 09:14 UTC, koalex commented on 1-module/4-task/index.js
> +  if (str.toLowerCase().includes('1xbet') || str.toLowerCase().includes('xxx')) {
Можно так:
`return str.toLowerCase().includes('1xbet') || str.toLowerCase().includes('xxx');`

2022-12-22 09:14 UTC, merged